<table align="left">
  <td>
<a href="https://colab.research.google.com/github/marco-canas/Fundamentos-de-la-aritm-tica/blob/main/clases/criba.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

## [Video de apoyo]()

# Probar por inducción matemática que las exponenciales siempre que ganan a la cuadráticas 


Prube por inducción matemática que 


$$ n^{2} < 2^{n}, \ \ \ \ \ \ n > 4 $$


Y haga también las siguientes verificaciones y representaciones tabulares y gráficas. 



In [3]:
import pandas as pd 
import numpy as np 

In [4]:
n = np.arange(5, 30) 
n 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
exponencial = np.array([2**t for t in n])
exponencial 

array([       32,        64,       128,       256,       512,      1024,
            2048,      4096,      8192,     16384,     32768,     65536,
          131072,    262144,    524288,   1048576,   2097152,   4194304,
         8388608,  16777216,  33554432,  67108864, 134217728, 268435456,
       536870912])

In [6]:
cuadratica = np.array([t**2 for t in n]) 
cuadratica 

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196, 225, 256, 289,
       324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841])

# Representación tabular de la desigualdad

In [7]:
tabla = pd.DataFrame({'$n$': n, 'exponencial':exponencial, 'cuadratica':cuadratica}) 
tabla 

$n$  exponencial  cuadratica
0     5           32          25
1     6           64          36
2     7          128          49
3     8          256          64
4     9          512          81
5    10         1024         100
6    11         2048         121
7    12         4096         144
8    13         8192         169
9    14        16384         196
10   15        32768         225
11   16        65536         256
12   17       131072         289
13   18       262144         324
14   19       524288         361
15   20      1048576         400
16   21      2097152         441
17   22      4194304         484
18   23      8388608         529
19   24     16777216         576
20   25     33554432         625
21   26     67108864         676
22   27    134217728         729
23   28    268435456         784
24   29    536870912         841

# Representación gráfica de la desigualdad

In [1]:
import matplotlib.pyplot as plt 
limite = 3  

plt.scatter(n[:limite], cuadratica[:limite], color = 'blue', label = 'cuadratica $n^{2}$')
plt.scatter(n[:limite], exponencial[:limite], color = 'red', label = 'exponencial $2^{n}$')

plt.grid(alpha = 0.4)
plt.legend()


NameError: name 'n' is not defined

## Inferencias e interpretaciones al gráfico

* Efectivamente el gráfico verificó que $2^{n} > n^{2}$ para cada $n \in \mathbb{N}$, con $n = 0, 1, 2, 3, \ldots$

## Referentes  